FROM node:24-alpine

WORKDIR /src

RUN npm install --global pnpm@11.25.0 \
    && apk add --no-cache wget

COPY package.json pnpm-workspace.yaml pnpm-lock.yaml ./
COPY apps/web/package.json apps/web/package.json
RUN pnpm install --frozen-lockfile

CMD ["pnpm", "--filter", "@agent-board/web", "dev"]
